---
title: "VLP Brown - Example C13 - no heat transfer"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{VLP Brown - Example C13 - no heat transfer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=F, error=T, message=F, warning=F}
knitr::opts_chunk$set(echo=T, comment=NA, error=T, warning=F, message = F, fig.align = 'center')
```


## Calculate VLP using Hagedorn-Brown (no heat transfer)
* vertical well


```{r rows.print=30}
library(rNodal)

# Example from C.13 in Brown
# P2 (pressure at end point is given). 
# The question is: what is the length of the tubing.
# P2 = 1000 psia

input.example.C13 <- setWellInput(
                        field.name = "HAGBR.MOD", 
                        well.name = "Brown_C13", 
                        depth.wh = 0, depth.bh = 2670, 
                        diam.in = 1.995, 
                        GLR = 500, 
                        liq.rt = 1000, 
                        wcut = 0.6, 
                        thp = 500, 
                        tht = 120, 
                        bht = 150, 
                        API = 22, 
                        gas.sg = 0.65, 
                        wat.sg = 1.07, 
                        if.tens = 30)


well.model <- setVLPmodel(vlp.model = "hagbr.mod", 
                          segments = 11, 
                          tol = 0.000001)

c13_output <- runVLP(well.input = input.example.C13, well.model)
c13_output
```

```{r, fig.height=6, fig.width=6}
library(ggplot2)
library(scales)

ggplot(c13_output, aes(x = pres, y = depth)) +
  scale_y_reverse(breaks = scales::pretty_breaks(n= 20)) +
  geom_line() +
  geom_point()

ggplot(c13_output, aes(x = pres, y = depth)) +
  scale_x_continuous(limits = c(500, 1300), breaks = seq(500, 1300, 100)) +
  scale_y_reverse(limits = c(2700, 0), breaks = seq(0, 2700, 100)) +
  geom_line() +
  geom_point()

```

