---
title: "Brown C13 Example"
output: html_notebook
---

```{r}
# source all the files
# library(R.utils)
# sourceDirectory("../../R")

# file.sources = list.files(c("./R"), 
#                           pattern="\\.R$", full.names=TRUE, 
#                           ignore.case=TRUE)
# sapply(file.sources,source,.GlobalEnv)
```

```{r rows.print=30}
# Example from C.13 in Brown
# P2 (pressure at end point is given). THe question is: what is the length of the tubing.
# P2 = 1000 psia


input.example.C13 <- setWellInput(field.name = "HAGBR.MOD",
                                    well.name = "Brown_C13", 
                                    depth.wh = 0, depth.bh = 2670, diam.in = 1.995, 
                                    GLR = 500, liq.rt = 1000, wcut = 0.6, 
                                    thp = 500, tht = 120, bht = 150, 
                                    API = 22, gas.sg = 0.65, wat.sg = 1.07, if.tens = 30)


well.model <- setVLPmodel(vlp.model = "hagbr.mod", segments = 29, tol = 0.000001)

runVLP(well.input = input.example.C13, well.model)
```



