---
title: "sandbox 05: obtain the VLP models with sapply"
output: html_notebook
---

## End result

```{r}
# script that shows a dataframe of all VLP models used over time

# build the dataset name, get the VLP model name
library(dplyr)

# get a listing of HDF5 objects
hFile <- "./data/WOODLIB.02.hdf5"
my.var <- "vlp.model"
df <- h5ls(hFile)

# get a vector of those datasets named "vlp.model"
df2 <- df %>%
    filter(name == my.var) %>%
    select(group)
v2 <- df2$group
v3 <- paste(v2, my.var, sep = "/")

# create dataframe for final output
df.vlp <- data.frame(model = sapply(v3, function(x) h5read(hFile, x)))
df.vlp
H5close()
```


## How was it done or "the making of"

```{r rows.print=30}
# get all the objects
df <- h5ls("./data/WOODLIB.01.hdf5")
df
H5close()
```

```{r}
# get a vector of those datasets named "vlp.model"
library(dplyr)

my.var <- "vlp.model"

df2 <- df %>%
    filter(name == my.var) %>%
    select(group)

v2 <- df2$group
v2
```

```{r}
# test joining group paths
ds.name <- paste(v2[1], my.var, sep = "/")
h5read("./data/WOODLIB.01.hdf5", ds.name)
```

```{r}
# vector joining of group paths and get values of vlp.model with sapply
v3 <- paste(v2, my.var, sep = "/")

sapply(v3, function(x) h5read("./data/WOODLIB.01.hdf5", x))
H5close()
```





```{r}
# get a vector of run date plus the model variable
v3 <- paste(v2, my.var, sep = "/")
v3
```

