---
title: "VLP Brown - Example C13"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{VLP Brown - Example C13}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r rows.print=30}
library(rNodal)

# Example from C.13 in Brown
# P2 (pressure at end point is given). 
# The question is: what is the length of the tubing.
# P2 = 1000 psia


input.example.C13 <- setWellInput(field.name = "HAGBR.MOD",
                                    well.name = "Brown_C13", 
                                    depth.wh = 0, depth.bh = 2670, diam.in = 1.995, 
                                    GLR = 500, liq.rt = 1000, wcut = 0.6, 
                                    thp = 500, tht = 120, bht = 150, 
                                    API = 22, gas.sg = 0.65, wat.sg = 1.07, if.tens = 30)


well.model <- setVLPmodel(vlp.model = "hagbr.mod", segments = 11, tol = 0.000001)

df <- runVLP(well.input = input.example.C13, well.model)
df
```

p30 = 1043.8745
p30 = 1043.8793
p30 = 1045.1834
p30 = 1043.1091 (after using p.avg and t.avg)
p30 = 1043.1094 (after using p.avg, t.avg, p0 = p.calc)

[link to hdf5 file](C:\Users\msfz751\AppData\Local\Temp\RtmpEbxvPR\file40c0446c2f7.h5)

[hdf5 in inst/extdata](I:\src\rNodal\inst\extdata\brown_c13.h5)

[h5](C:\Users\msfz751\AppData\Local\Temp\RtmpM3UF3e\file526835c54c20.h5)



        0	    0   	500.0	135.8
        242.7	242.7	563.1	137.9
        485.5	485.5	627.5	139.8
        728.2	728.2	693.1	141.6
        970.9	970.9	759.8	143.4
        1213.6	1213.6	827.6	144.9
        1456.4	1456.4	896.5	146.3
        1699.1	1699.1	966.4	147.6
        1941.8	1941.8	1037.3	148.6
        2184.5	2184.5	1109.3	149.3
        2427.3	2427.3	1182.2	149.8
        2670.0	2670.0	1255.9	150.0
        
        
## Heat transfer calculations

```{r}
well_table <- df[, c("depth", "dL", "pres", "temp")]
well_table
```

```{r}
# parameters necessary to calculate the fluid temperature
theta   <-  pi /2
diam.in <- 1.995
diam.ft <- diam.in / 12
tht     <- 120
bht     <- 150
depth   <- 2670
ge      <- (bht - tht) / depth
mass.rate <- 228145
U <-  2
# U <- 4
cp.avg <- (0.53 + 0.5 + 1 ) / 3

# calculate dT/dx for the well
rNodal:::temp.fluid(well_table, theta, depth, bht, tht, U, cp.avg, diam.ft, mass.rate)
```

```{r}
input.example.C13 <- setWellInput(field.name = "HAGBR.MOD",
                                    well.name = "Brown_C13", 
                                    depth.wh = 0, depth.bh = 2670, diam.in = 1.995, 
                                    GLR = 500, liq.rt = 1000, wcut = 0.6, 
                                    thp = 500, tht = 120, bht = 150, 
                                    API = 22, gas.sg = 0.65, wat.sg = 1.07, if.tens = 30)
getBasicCalcs(input.example.C13)
```


